### ISSUE TITLE
 Server error

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui#5]
Today we got this error when we tried to import some workstations. After this error, the workstations file is empty!

Version: 1.0.5-0

**Request**
POST /api/lm/workstations
**Type**
ValueError
**Message**
dict contains fields not in fieldnames: null

**Traceback:**

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lm_workstations/views.py", line 46, in handle_api_workstations
    csv.DictWriter(f, delimiter=';', fieldnames=fieldnames).writerows(data)
  File "/usr/lib/python2.7/csv.py", line 153, in writerows
    rows.append(self._dict_to_list(rowdict))
  File "/usr/lib/python2.7/csv.py", line 144, in _dict_to_list
    ", ".join(wrong_fields))
ValueError: dict contains fields not in fieldnames: null`

**Comment by netzint** [comment]
Fixed in 1.0.6-0.. package will be soon available in lmn repo.
